name: Build a container image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  envoy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'google/android-emulator-container-scripts'
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tsuzu
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove copying jwks
        run: |
          grep -v jwt_secrets_pub js/docker/envoy.Dockerfile > /tmp/envoy.Dockerfile
          mv /tmp/envoy.Dockerfile js/docker/envoy.Dockerfile
      - name: Replace jwks path
        env:
          FORCE_COLOR: 3
        run: |
          npx zx <<'EOF'
          
          const name = 'js/docker/envoy.yaml';
          const replaced = fs.readFile(name).replace('/etc/jwt_secrets_pub.jwks', '/etc/jwks/jwt_secrets_pub.jwks');
          fs.writeFile(name, replaced);
          
          EOF

      - uses: docker/build-push-action@v2
        with:
          context: js/docker
          file: js/docker/envoy.Dockerfile
          push: true
          tags: ghcr.io/tsuzu/android-emulator-envoy
          cache-from: type=gha
          cache-to: type=gha,mode=max
  jwt_signer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'google/android-emulator-container-scripts'
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tsuzu
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: js/jwt-provider
          push: true
          tags: ghcr.io/tsuzu/android-emulator-jwt-signer
          cache-from: type=gha
          cache-to: type=gha,mode=max
  nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'google/android-emulator-container-scripts'
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tsuzu
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: js
          file: js/docker/nginx.Dockerfile
          push: true
          tags: ghcr.io/tsuzu/android-emulator-nginx
          cache-from: type=gha
          cache-to: type=gha,mode=max
